[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_APP_ENV = "production"

[context.production.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyBvaPFLFgPkCyPuByFia-ghBtc27sP3P5E"
  VITE_FIREBASE_AUTH_DOMAIN = "makemoneymove-b8afb.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "makemoneymove-b8afb"
  VITE_FIREBASE_STORAGE_BUCKET = "makemoneymove-b8afb.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "1037768554358"
  VITE_FIREBASE_APP_ID = "1:1037768554358:web:922e4d1870a56db7c6ec57"
  VITE_FIREBASE_MEASUREMENT_ID = "G-7NLTY084TG"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  autoLaunch = false

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = """
      default-src 'self' https://*.firebaseapp.com https://*.googleapis.com https://*.google.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.firebaseapp.com https://*.googleapis.com https://*.google.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https://*.googleapis.com https://*.gstatic.com https://*.google.com;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://*.firebaseio.com https://*.googleapis.com wss://*.firebaseio.com https://*.google.com https://*.cloudfunctions.net;
      frame-src 'self' https://*.firebaseapp.com https://*.googleapis.com https://*.google.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      worker-src 'self' blob:;
      """
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Resource-Policy = "cross-origin"
