[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_APP_ENV = "production"
  SITE_URL = "https://moneymovenow.site"

[context.production.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyD3fcvbYGwOTsJDbvko7c6bSu_QeFw_eyQ"
  VITE_FIREBASE_AUTH_DOMAIN = "moneymovenow-62870.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "moneymovenow-62870"
  VITE_FIREBASE_STORAGE_BUCKET = "moneymovenow-62870.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "471416228349"
  VITE_FIREBASE_APP_ID = "1:471416228349:web:7654ba69328f78eaf0b194"
  VITE_FIREBASE_MEASUREMENT_ID = "G-2YXQLSQNHR"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  autoLaunch = false

# Legal pages
[[redirects]]
  from = "/privacy-policy"
  to = "/legal/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/terms-of-service"
  to = "/legal/terms-of-service.html"
  status = 200

# Handle SPA routing (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = """
      default-src 'self' http://localhost:* https://*.google.com https://*.googleapis.com https://*.gstatic.com https://*.firebaseapp.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' http://localhost:* https://*.google.com https://*.googleapis.com https://*.gstatic.com https://*.firebaseapp.com;
      style-src 'self' 'unsafe-inline' https://*.googleapis.com https://*.gstatic.com;
      img-src 'self' data: https://*.googleapis.com https://*.gstatic.com https://*.google.com;
      font-src 'self' https://*.gstatic.com;
      connect-src 'self' http://localhost:* ws://localhost:* https://*.firebaseio.com https://*.googleapis.com wss://*.firebaseio.com https://*.google.com https://*.cloudfunctions.net https://*.gstatic.com https://identitytoolkit.googleapis.com;
      frame-src 'self' http://localhost:* https://*.firebaseapp.com https://*.google.com https://*.gstatic.com https://accounts.google.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://accounts.google.com;
      worker-src 'self' blob:;
      """
    Cross-Origin-Opener-Policy = "unsafe-none"
    Cross-Origin-Resource-Policy = "cross-origin"
    Cross-Origin-Embedder-Policy = "unsafe-none"
